version: "3"

volumes:
  mysql:
    driver: local

services:
  ppm:
    build:
      context: .
      dockerfile: ./docker/ppm/Dockerfile
    container_name: mahjong_ppm
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - mahjong

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mahjong_mysql
    environment:
      MYSQL_DATABASE: "default"
      MYSQL_USER: "default"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      TZ: "UTC"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "53306:3306"
    networks:
      - mahjong
    command: --innodb-use-native-aio=0

  composer:
    image: composer:1.10.19 # 1.10.20からphp8
    volumes:
      - ./.:/app
    command: echo true
    networks:
      - mahjong

networks:
  mahjong:
