version: "3"

volumes:
  mysql:
    driver: local

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: mahjong_nginx
    volumes:
      - ./:/var/www
    ports:
      - "50080:80"
    depends_on:
      - php
    networks:
      - mahjong

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: mahjong_php
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - mahjong

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mahjong_mysql
    environment:
      MYSQL_DATABASE: "default"
      MYSQL_USER: "default"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      TZ: "UTC"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "53306:3306"
    networks:
      - mahjong
    command: --innodb-use-native-aio=0

networks:
  mahjong:
